<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQxIORKl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQxIORKl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQxIORKl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQxIORKl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQxIORKl\App_KernelDevDebugContainer([
    'container.build_hash' => 'QxIORKl',
    'container.build_id' => 'b53806d7',
    'container.build_time' => 1588872459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQxIORKl');
